### ISSUE TITLE
Could not parse line: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }

### ISSUE THREAD

**Issue by kmpm** [marcograss/routerosbackuptools#1]
I get an error trying to bruteforce a backup file. (It's the only operation i have tried so far).
The 'rockyou.txt' wordlist have been successfully used with other software.

Running in WSL2 on Windows 10 x64
```
rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

```
$ RUST_BACKTRACE=full cargo run --release -- bruteforce -i WSP-Router_v6.29.1.bac
kup -w rockyou.txt
    Finished release [optimized] target(s) in 0.18s
     Running `target/release/routerosbackuptools bruteforce -i WSP-Router_v6.29.1.backup -w rockyou.txt`
** Bruteforce Backup Password **
** Backup Info **
RouterOS Encrypted Backup (rc4-sha1)
Length: 68386 bytes
Salt (hex): [4e, b8, 9c, cd, 78, 66, 67, 12, 2, 85, b6, 5d, 5c, 6b, 3, b9, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 41, 6d, a8]
Magic Check (hex): c34b7996
thread 'main' panicked at 'Could not parse line: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', src/lib.rs:566:20
stack backtrace:
   0:     0x7f28922b12dc - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f28922b12dc - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f28922b12dc - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f28922b12dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f28922d07fc - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x7f28922ad533 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x7f28922b3902 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f28922b3902 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f28922b3902 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x7f28922b34e5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x7f28922b3f53 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x7f28922b3c70 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x7f28922b1784 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x7f28922b39a9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x7f289221d3e1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x7f289221d473 - core::result::unwrap_failed::ha0327e3803285d6e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
  16:     0x7f2892232dd3 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h7aa8dd6619c118b8
  17:     0x7f28922307f4 - routerosbackuptools::read_wordlist_file::hb5695234fd382f29
  18:     0x7f2892221c9e - routerosbackuptools::main::h6659af2025959ad1
  19:     0x7f289222ab43 - std::sys_common::backtrace::__rust_begin_short_backtrace::h63465ca4296e1276
  20:     0x7f289222d419 - std::rt::lang_start::{{closure}}::h730da29801f22a44
  21:     0x7f28922b0990 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  22:     0x7f28922b0990 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  23:     0x7f28922b0990 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  24:     0x7f28922b0990 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  25:     0x7f28922b0990 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  26:     0x7f28922b0990 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  27:     0x7f28922b0990 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  28:     0x7f28922b0990 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  29:     0x7f28922b0990 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  30:     0x7f2892224752 - main
  31:     0x7f2891e540b3 - __libc_start_main
  32:     0x7f289221dafe - _start
  33:                0x0 - <unknown>
```

**Comment by kmpm** [comment]
It might be the 'rockyou.txt' file anyway.
```shell
# check what type of file it is
$ file rockyou.txt
rockyou.txt: UTF-8 Unicode text

# test the whole file
$ iconv -f UTF-8 -t UTF-8 rockyou.txt -o /dev/null; echo $?
iconv: illegal input sequence at position 5079963
1

# strip bad characters
iconv -f UTF-8 rockyou.txt -t UTF-8//IGNORE -o rockme.txt

# try again
$ RUST_BACKTRACE=full cargo run --release -- bruteforce -i WSP-Router_v6.29.1.bac
kup -w rockyou.txt
    Finished release [optimized] target(s) in 0.33s
     Running `target/release/routerosbackuptools bruteforce -i WSP-Router_v6.29.1.backup -w rockyou.txt`
** Bruteforce Backup Password **
** Backup Info **
RouterOS Encrypted Backup (rc4-sha1)
Length: 68386 bytes
Salt (hex): [4e, b8, 9c, cd, 78, 66, 67, 12, 2, 85, b6, 5d, 5c, 6b, 3, b9, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 41, 6d, a8]
Magic Check (hex): c34b7996
Password NOT found
```

Close the issue if you want to.
